### PR TITLE
Control the range on angles to search for and minor fixes

### PR DESCRIPTION
**Pull request by giocard**
I changed the code to handle any range of angles requested by the user, with the only constrain of not extending beyond a total of 180 degrees. The changes are backward compatible except when recording: before there was just an argument, _histogram_, to define the starting angle, while now there are two, _histogram_start_ and _histogram_end_, to define both starting and ending angles. 
I modified the test because the expected output was incorrect
I modified the kernel of the Sobel filter, following the issue reported after the discussion on the forum.
I adapted the documentation to reflect these changes.

### CODE REVIEW

**Comment by tinevez** [comment]
Hi @giocard 
This PR has one problem still: When limiting the range of the angle to analyse, the limits are not acknowledged when generating the color map of angle. 

- When you use the Fourier method it gives nonsense. 
- With the gradient orientation it works.  
- But the color wheel does not reflect the bounds.

For instance, here is what I get when using -20º and 20º as limits, with the gradient orientation method. Note the stem of the leaf. The color there are correct, but on the color wheel the red color still matches -90º and 90º.

Could you address that too?

screenshot

**Comment by giocard** [comment]
Hi @tinevez ,
with the fourier method, the way the colormap is computed leads to an intrinsic stripe effect. While it is not always evident when analysing over the full range of possible directions, with limited ranges the effect is enhanced. Honestly I already thought about it, but I can't see a way to solve this issue. The only way I could think is to still calculate the weights over the full range when the colormap is requested, whatever range is actually specified, but that could explode the computational time. Keep in mind that this issue with the colormap is not an actual limitation of the fourier method, since the directionality analysis is always correct, independently of the range of directions selected (i.e. the histogram in a given range is the same, except for a scaling factor, either if I perform the analysis on 180 degrees or on just that range). This is because the colormap is calculated separately, and does not reflect the accuracy of the method.
Regarding the color wheel,  I modified it in a way that probably is not intuitive: when indicating a range of directions, the wheel remains the same, but the angles associated to each color change. In fact if you move the cursor over the colors in the wheel you will read the corresponding angles, and the values are consistent with the colors in the colormap. I just modified the colorwheel to visually help the user to understand how to interpret the colors (once I understand what I am doing wrong, the numbers would be right-aligned). Would that be acceptable? Open to suggestions on both topics.

0to60_color_wheel_proposed
full_range_color_wheel_proposed

**Comment by tinevez** [comment]
@giocard I think that the color wheel improvement you propose is great! Go for it!

**Comment by giocard** [comment]
Done!

**Comment by tinevez** [comment]
And released!
@giocard do you care to make an announcement on the forum?

**Pull request merged**
